### ISSUE TITLE
Obsolete async method in base class should also be generated obsolete in overrides

### ISSUE THREAD

**Issue by bahusoid** [maca88/AsyncGenerator#102]
To avoid breaking changes I have a need to obsolete no more generated async method.
But added manually obsolete async method leads async generator to generate non obsolete overrides in ancestors.
See full details here:
https://github.com/nhibernate/nhibernate-core/pull/1718#discussion_r192739208

**Comment by fredericDelaporte** [comment]
This case is a bit wicked indeed. We need to somehow artificially keep in place async counterparts for visible methods which were once using some calls with async counterparts, but which does no more.

The async generator rightfully removes their async counterpart in such case, but this is then a breaking change. So we have added back the method manually in the non-generated file, obsoleted.

In this case, the manually added method is abstract, and needs to be overridden in derived classes.

The async generator generates these overrides, which is fine, but they lack the `Obsolete` attribute, which does not suit our needs. Moreover it generates a warning since the base method is obsoleted, but not the generated override. (Similarly if an async method was put in an interface, and was having concrete implementations generated, they should also copy the `Obsolete` attribute of the base declaration; I have not checked this case.)

As a workaround, putting manually these overrides in the derived class non-generated files does not work: the async generator still additionally generates them, causing the code to be invalid. I have also looked for a way to disable `scanForMissingAsyncMembers` only for this method but have not found one.

**Comment by maca88** [comment]
[I've added a PR](https://github.com/maca88/AsyncGenerator/pull/104) that fixes both issues:
1. Manually add the abstract async method with an `Obsolete` attribute to the original file and the generator will generate all overrides with the `Obsolete` attribute as well.
2. Manually add the abstract async method and all overrides with the `Obsolete` attribute to the original files and the generator will not duplicate them anymore.

**Comment by fredericDelaporte** [comment]
Thanks @maca88.
