### ISSUE TITLE
NUnitAsyncCounterpartsFinder does not handle ignored returned value

### ISSUE THREAD

**Issue by fredericDelaporte** [maca88/AsyncGenerator#47]
```C#
Assert.That(() => query.ToList(), Throws.Exception);
```

Is converted to:

```C#
Assert.That(() => query.ToListAsync(), Throws.Exception);
```

Instead of:

```C#
Assert.That(async () => await query.ToListAsync(), Throws.Exception);
```

While

```C#
List<Dog> list;
Assert.That(() => list = query.ToList(), Throws.Exception);
```

Is correctly converted to:

```C#
List<Dog> list;
Assert.That(async () => list = await query.ToListAsync(), Throws.Exception);
```

Found with this [test](https://github.com/fredericDelaporte/nhibernate-core/blob/master/src/NHibernate.Test/Linq/ByMethod/CastTests.cs#L33). This causes the exception to not occur inside the assertion check and it gets caught by NUnit which report it as failure, instead of being swallowed as being expected.
(But well, the valid syntax still fails as uncaught, and the workaround too, weird... Maybe there is a NUnit bug on top of that. Confirmed : see [this](https://github.com/nunit/nunit/issues/1899).)

**Comment by maca88** [comment]
There is no benefit by adding the `async`/`await` keywords for the first example as both anonymous functions return a `Task` that NUnit has to deal with, it will just add an additional overhead because of the async internal [state machine](https://weblogs.asp.net/dixin/understanding-c-sharp-async-await-1-compilation). As you already discovered the problem is with the second parameter `Throws.Exception` that does not support tasks as return type. When using `Throws.InstanceOf<Exception>()` instead, it will wait for the returned task [to complete](https://github.com/nunit/nunit/blob/7b87bdc7b48ee1b13023dd282efea449c2d66b81/src/NUnitFramework/framework/Constraints/ThrowsExceptionConstraint.cs#L74) by using the [Task.Wait method](https://github.com/nunit/nunit/blob/7b87bdc7b48ee1b13023dd282efea449c2d66b81/src/NUnitFramework/framework/Internal/AsyncInvocationRegion.cs#L109).

**Comment by fredericDelaporte** [comment]
Yes your are right, sorry.
