### ISSUE TITLE
Add support for different awaitable tasks like ValueTask<T>

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#64]
This has 2 main streams of work:

1. Search for async counterparts which return awaitable results other than `Task<>/Task`
2. Ability to specify what type shall the generated async code return.

**Comment by hazzik** [comment]
I've updated the description

**Comment by hazzik** [comment]
@maca88 we now need this, if we want to support .NET Standard 2.1 and above. Some async methods in ADO.NET return `ValueTask<>`.

**Comment by hazzik** [comment]
At least first part

**Comment by maca88** [comment]
Ok, I will try to implement it next week as I will have more free time.

**Comment by maca88** [comment]
The feature was added, but I am not sure how it will be used for NHibernate. In order to successfully generate `BeginTransactionAsync`, I've added an option to generate async methods with preprocessor directives (#165). [Here](https://github.com/maca88/nhibernate-core/commit/85f640ed19840bd370e7299016ecc662f9b930af) you can see what would be generated for making `BeginTransaction` async. Because some of the new generated async methods are used in existing methods, I had to add `AsyncExtensions` class, which contains extension methods for missing async methods that are present only in `netstandard2.1`.

**Comment by hazzik** [comment]
Why it generated `ValueTask<>` for ISession?

**Comment by maca88** [comment]
Because it is [explicitly configured](https://github.com/maca88/nhibernate-core/commit/85f640ed19840bd370e7299016ecc662f9b930af#diff-60e3e40b5223a1c12eeb3d32a9be6ceb498de4f79d2d62008da4a6330e30bfdfR339) to convert it to `ValueTask`. I added this because `DbConnection.BeginTransactionAsync` is the only async method that is called inside `ISession.BeginTransactionAsync`.

**Comment by hazzik** [comment]
> I added this because DbConnection.BeginTransactionAsync is the only async method that is called inside ISession.BeginTransactionAsync.

But it should not be matter what actual thing is returned by called methods. Because you're awaiting it anyway. It only matters when you want to directly return the task with changing the type:

```csharp
    public Task<DbTransaction> BeginTransactionAsync(DbConnection c) {
        return c.BeginTransactionAsync(); // this does not compile
    }
``` 
But the following 2 snippets work fine:

```csharp
    public Task<DbTransaction> BeginTransactionAsync(DbConnection c) {
        return c.BeginTransactionAsync().AsTask();
    }
``` 
```csharp
    public async Task<DbTransaction> BeginTransactionAsync(DbConnection c) {
        return await c.BeginTransactionAsync();
    }
```

**Comment by hazzik** [comment]
> The feature was added, but I am not sure how it will be used for NHibernate.

I think it should be exactly as you've done it or very close.

**Comment by maca88** [comment]
In case `BeginTransactionAsync` method will be added in a minor release (e.g. 5.4), then probably it shouldn't be added to the `ISession` interface? I am asking this because currently there is no option in the generator for not generating specific methods (e.g. `ISession.BeginTransactionAsync` ). In case such setting is needed, then I will add it.

**Comment by fredericDelaporte** [comment]
Or we will have to copy/paste the generated code into a temporary "manual" implementation using a transitional interface, with async generator set to ignore `BeginTransaction`, until next major.
