### ISSUE TITLE
Too much logs?

### ISSUE THREAD

**Issue by fredericDelaporte** [maca88/AsyncGenerator#75]
When generating async code for NHibernate, the console is flooded with logs, especially warnings.
Usually warnings are there to ask for a fix, but here we just live with most of them "since the beginning".
If any serious one is added, warning at a thing we should really consider for having a sound async implementation, it can only go unnoticed.

I have suspected they have an impact on performances, and that is the case: raising the log level to `ERROR` cut down the generation time, from an initial value of more than 120 seconds on my laptop to less than 90 seconds.

Some of them could likely be fixed on NHibernate side (configuration of generator or code adjustment for better async implementation), but others are maybe just excessive logging. Or logging that should have an option for being disabled.

By example, all warnings about things that cannot get converted to async could have an option for emitting them, maybe something like a `diagnoseMissingAsync`. Since we are flooded by many of them that will not get fixed any time soon, better have a way to see them only when we intend to work on them. Seeing them on every routine generation has currently no purpose since they are so numerous, we will not spot new ones.

But of course warnings about incorrect settings should stay and get fixed by the async user, provided they are not warnings about an unset setting having a sound default (like the `Optional` thing I was mentioning [here](https://github.com/maca88/AsyncGenerator/commit/c977e421b0f1a76629bd5d65d40c4f53b6136d92#r26165675), now fixed).

**Comment by maca88** [comment]
I agree with you, the current logs are not useful for bigger project like NHibernate as there is a lot of noise. I will revisit the current logging and try to minimize the warnings, so that only the relevant ones will be shown, for others, will probably add some configuration as you already suggested.

Until today I never had performance problems with the logging when running the generator on NHibernate project, the total time was around 100 seconds (from `0.6.0` onwards), but now was 150 seconds on my machine. With the yesterday's fix, the total time went back to 100 seconds. It's really strange that this issue didn't shown on my computer before.

I am planning to do the logging change in the followings days and then release a new version.

**Comment by hazzik** [comment]
I can confirm that on my machine at least 1/3 time it just displays logs.

**Comment by maca88** [comment]
I finally revisited the logging to be more useful and readable. [This log](https://gist.github.com/maca88/8e3315119144690e043b29e0470c234a) will be produced by default when running the generator for the NHibernate project. As it can be seen from the log, diagnostics are group by the document, type and method for easier reading. In order to ignore a document, type or method from being printed, the `DiagnoseDocument`, `DiagnoseType` and `DiagnoseMethod` options can be used ([example for ignoring a method](https://github.com/maca88/AsyncGenerator/blob/master/Source/AsyncGenerator.Tests/Diagnostics/Fixture.cs#L56)). The same options can be also used for diagnose a method from not being generated e.g.
```
diagnostics:
  diagnoseMethod:
  - name: Test2
    result: true
  - all: true
    result: false
```
which will diagnose and print only diagnostics for the `Test2` method.

**Comment by maca88** [comment]
Done by https://github.com/maca88/AsyncGenerator/commit/1dd41da80c5d0ad845d9325b3d78004a8c54e1ca
